### ISSUE TITLE
Add docs for the tasks container

### ISSUE THREAD

**Issue by m1212e** [DeutscheModelUnitedNations/munify-delegator#104]
The image can be rune in the "tasks mode" by changing the start command:

```yml
  delegator:
    image: deutschemodelunitednations/delegator:latest
    depends_on:
      - postgres
    ports:
      - 3000:3000
    # if you want to utilize a tasks container you can start the image with this instead
    # command: ["bun", "tasksMain.js"]
```

After completing tasks development we should add proper documentation on how that works and what you can do with that!
